<?xml version="1.0" encoding="utf-8"?><Database Name="SIGES" Class="SIGESDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-G4VRQFR\SQLEXPRESS;Initial Catalog=SIGES;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SIGESConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Administration_Evaluacion_Tienda" Member="Administration_Evaluacion_Tienda">
    <Type Name="Administration_Evaluacion_Tienda">
      <Column Name="IDEvaluacion" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NoEvaluacion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NombreAs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Evaluadores" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FModificacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NoReactivos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoRespuestas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Puntaje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Reactivos" Member="Administration_Evaluacion_Tienda_Reactivos" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda_Reactivos" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Resultados" Member="Administration_Evaluacion_Tienda_Resultados" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda_Resultados" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Soluciones" Member="Administration_Evaluacion_Tienda_Soluciones" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda_Soluciones" />
      <Association Name="User_Usuarios_Administration_Evaluacion_Tienda" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
      <Association Name="System_Areas_Administration_Evaluacion_Tienda" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.User_Usuarios" Member="User_Usuarios">
    <Type Name="User_Usuarios">
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CURP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="APaterno" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AMaterno" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDPerfil" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LVLPerfil" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NArea" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NSArea" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Asignacion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sitio" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDPadre" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CManejador" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FManejador" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CPlataforma" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FPlataforma" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FIngreso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FEgreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Usuarios_Administration_Evaluacion_Tienda" Member="Administration_Evaluacion_Tienda" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Administration_Evaluacion_Tienda" />
      <Association Name="User_Usuarios_Administration_Evaluacion_Tienda_Resultados" Member="Administration_Evaluacion_Tienda_Resultados" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Administration_Evaluacion_Tienda_Resultados" />
      <Association Name="User_Usuarios_System_Areas" Member="System_Areas" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="System_Areas" />
      <Association Name="User_Usuarios_System_Sis_Bitacora" Member="System_Sis_Bitacora" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="System_Sis_Bitacora" />
      <Association Name="User_Usuarios_System_Sis_Notificacion_Seguimiento" Member="System_Sis_Notificacion_Seguimiento" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="System_Sis_Notificacion_Seguimiento" />
      <Association Name="User_Usuarios_System_Supervision" Member="System_Supervision" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="System_Supervision" />
      <Association Name="User_Usuarios_Trainig_Cuestionario" Member="Trainig_Cuestionario" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Trainig_Cuestionario" />
      <Association Name="User_Usuarios_Trainig_Cuestionario_Respuestas_User" Member="Trainig_Cuestionario_Respuestas_User" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Trainig_Cuestionario_Respuestas_User" />
      <Association Name="User_Usuarios_Trainig_Cuestionario_Seguimiento" Member="Trainig_Cuestionario_Seguimiento" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Trainig_Cuestionario_Seguimiento" />
      <Association Name="User_Usuarios_Trainig_Cursos" Member="Trainig_Cursos" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Trainig_Cursos" />
      <Association Name="User_Usuarios_Trainig_Cursos_Seguimiento" Member="Trainig_Cursos_Seguimiento" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="Trainig_Cursos_Seguimiento" />
    </Type>
  </Table>
  <Table Name="dbo.Administration_Evaluacion_Tienda_Reactivos" Member="Administration_Evaluacion_Tienda_Reactivos">
    <Type Name="Administration_Evaluacion_Tienda_Reactivos">
      <Column Name="IDReactivo" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDEvaluacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoReactivo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Reactivo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IDSolucion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Valor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Administration_Evaluacion_Tienda_Reactivos_Administration_Evaluacion_Tienda_Soluciones" Member="Administration_Evaluacion_Tienda_Soluciones" ThisKey="IDReactivo" OtherKey="IDReactivo" Type="Administration_Evaluacion_Tienda_Soluciones" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Reactivos" Member="Administration_Evaluacion_Tienda" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Administration_Evaluacion_Tienda_Resultados" Member="Administration_Evaluacion_Tienda_Resultados">
    <Type Name="Administration_Evaluacion_Tienda_Resultados">
      <Column Name="IDResultado" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTienda" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDEvaluacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NoEvaluacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FEvaluacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Respuestas" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Resultados" Member="Administration_Evaluacion_Tienda" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda" IsForeignKey="true" />
      <Association Name="User_Usuarios_Administration_Evaluacion_Tienda_Resultados" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
      <Association Name="System_Sis_Tienda_Administration_Evaluacion_Tienda_Resultados" Member="System_Sis_Tienda" ThisKey="IDTienda" OtherKey="IDTienda" Type="System_Sis_Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Administration_Evaluacion_Tienda_Soluciones" Member="Administration_Evaluacion_Tienda_Soluciones">
    <Type Name="Administration_Evaluacion_Tienda_Soluciones">
      <Column Name="IDSolucion" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDEvaluacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDReactivo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoReactivo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Administration_Evaluacion_Tienda_Administration_Evaluacion_Tienda_Soluciones" Member="Administration_Evaluacion_Tienda" ThisKey="IDEvaluacion" OtherKey="IDEvaluacion" Type="Administration_Evaluacion_Tienda" IsForeignKey="true" />
      <Association Name="Administration_Evaluacion_Tienda_Reactivos_Administration_Evaluacion_Tienda_Soluciones" Member="Administration_Evaluacion_Tienda_Reactivos" ThisKey="IDReactivo" OtherKey="IDReactivo" Type="Administration_Evaluacion_Tienda_Reactivos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SIGES_Config" Member="SIGES_Config">
    <Type Name="SIGES_Config">
      <Column Name="IDConfiguracion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mision" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Vision" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Valores" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DireccionHost" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LogoTexto" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SesionAbierta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SerCorreo" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SerCorreoPort" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SerCorreoUser" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SerCorreoPass" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DirWEB" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato4" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Areas" Member="System_Areas">
    <Type Name="System_Areas">
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Carpeta" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Areas_Administration_Evaluacion_Tienda" Member="Administration_Evaluacion_Tienda" ThisKey="IDArea" OtherKey="IDArea" Type="Administration_Evaluacion_Tienda" />
      <Association Name="System_Areas_System_Areas_Recursos" Member="System_Areas_Recursos" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas_Recursos" />
      <Association Name="System_Areas_System_Areas_SubAreas" Member="System_Areas_SubAreas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas_SubAreas" />
      <Association Name="System_Areas_System_Incidencias_MesaAyuda" Member="System_Incidencias_MesaAyuda" ThisKey="IDArea" OtherKey="IDArea" Type="System_Incidencias_MesaAyuda" />
      <Association Name="System_Areas_System_Incidencias_MesaAyuda1" Member="System_Incidencias_MesaAyuda1" ThisKey="IDArea" OtherKey="IDArea" Type="System_Incidencias_MesaAyuda" />
      <Association Name="System_Areas_System_Incidencias_User_RInsidencias" Member="System_Incidencias_User_RInsidencias" ThisKey="IDArea" OtherKey="IDArea" Type="System_Incidencias_User_RInsidencias" />
      <Association Name="System_Areas_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias_User_RInsidencias_Seguimiento" ThisKey="IDArea" OtherKey="IDArea" Type="System_Incidencias_User_RInsidencias_Seguimiento" />
      <Association Name="System_Areas_System_Sis_Notificacion" Member="System_Sis_Notificacion" ThisKey="IDArea" OtherKey="IDArea" Type="System_Sis_Notificacion" />
      <Association Name="System_Areas_Trainig_Cuestionario" Member="Trainig_Cuestionario" ThisKey="IDArea" OtherKey="IDArea" Type="Trainig_Cuestionario" />
      <Association Name="System_Areas_Trainig_Cursos" Member="Trainig_Cursos" ThisKey="IDArea" OtherKey="IDArea" Type="Trainig_Cursos" />
      <Association Name="User_Usuarios_System_Areas" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Areas_Recursos" Member="System_Areas_Recursos">
    <Type Name="System_Areas_Recursos">
      <Column Name="IDRecurso" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FModificacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Areas_System_Areas_Recursos" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Areas_SubAreas" Member="System_Areas_SubAreas">
    <Type Name="System_Areas_SubAreas">
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="NoSubArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDEncargado2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NEncargado2" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TelefonoE2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorreoE2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDEncargado3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NEncargado3" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TelefonoE3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorreoE3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Areas_System_Areas_SubAreas" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Incidencias" Member="System_Incidencias">
    <Type Name="System_Incidencias">
      <Column Name="IDIncidencia" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NoSoluciones" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Reporte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Incidencias_System_Incidencias_MesaAyuda" Member="System_Incidencias_MesaAyuda" ThisKey="IDIncidencia" OtherKey="IDIncidencia" Type="System_Incidencias_MesaAyuda" />
      <Association Name="System_Incidencias_System_Incidencias_User_RInsidencias" Member="System_Incidencias_User_RInsidencias" ThisKey="IDIncidencia" OtherKey="IDInsidencia" Type="System_Incidencias_User_RInsidencias" />
      <Association Name="System_Incidencias_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias_User_RInsidencias_Seguimiento" ThisKey="IDIncidencia" OtherKey="IDIncidencia" Type="System_Incidencias_User_RInsidencias_Seguimiento" />
    </Type>
  </Table>
  <Table Name="dbo.System_Incidencias_MesaAyuda" Member="System_Incidencias_MesaAyuda">
    <Type Name="System_Incidencias_MesaAyuda">
      <Column Name="IDMesaAyuda" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDIncidencia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NoSolucion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FModificacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NoPaso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Areas_System_Incidencias_MesaAyuda" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="System_Areas_System_Incidencias_MesaAyuda1" Member="System_Areas1" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="System_Incidencias_System_Incidencias_MesaAyuda" Member="System_Incidencias" ThisKey="IDIncidencia" OtherKey="IDIncidencia" Type="System_Incidencias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Incidencias_User_RInsidencias" Member="System_Incidencias_User_RInsidencias">
    <Type Name="System_Incidencias_User_RInsidencias">
      <Column Name="IDRInsidencia" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDInsidencia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDTienda" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoInsidencia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Incidencias_User_RInsidencias_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias_User_RInsidencias_Seguimiento" ThisKey="IDRInsidencia" OtherKey="IDRInsidencia" Type="System_Incidencias_User_RInsidencias_Seguimiento" />
      <Association Name="System_Areas_System_Incidencias_User_RInsidencias" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="System_Incidencias_System_Incidencias_User_RInsidencias" Member="System_Incidencias" ThisKey="IDInsidencia" OtherKey="IDIncidencia" Type="System_Incidencias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias_User_RInsidencias_Seguimiento">
    <Type Name="System_Incidencias_User_RInsidencias_Seguimiento">
      <Column Name="IDSeguimiento" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NombreAs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDIncidencia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDRInsidencia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaInsidencia" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaSolucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Areas_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="System_Incidencias_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias" ThisKey="IDIncidencia" OtherKey="IDIncidencia" Type="System_Incidencias" IsForeignKey="true" />
      <Association Name="System_Incidencias_User_RInsidencias_System_Incidencias_User_RInsidencias_Seguimiento" Member="System_Incidencias_User_RInsidencias" ThisKey="IDRInsidencia" OtherKey="IDRInsidencia" Type="System_Incidencias_User_RInsidencias" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Inf_Estados" Member="System_Inf_Estados">
    <Type Name="System_Inf_Estados">
      <Column Name="IDEstado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Abrev" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Inf_Estados_System_Inf_Municipios" Member="System_Inf_Municipios" ThisKey="IDEstado" OtherKey="IDEstado" Type="System_Inf_Municipios" />
      <Association Name="System_Inf_Estados_System_Sis_Tienda" Member="System_Sis_Tienda" ThisKey="IDEstado" OtherKey="IDEstado" Type="System_Sis_Tienda" />
    </Type>
  </Table>
  <Table Name="dbo.System_Inf_Localidades" Member="System_Inf_Localidades">
    <Type Name="System_Inf_Localidades">
      <Column Name="IDLocalidad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMunicipio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Longitud" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Altitud" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(10,7) NOT NULL" CanBeNull="false" />
      <Column Name="Lng" Type="System.Decimal" DbType="Decimal(10,7) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Inf_Localidades_System_Sis_Tienda" Member="System_Sis_Tienda" ThisKey="IDLocalidad" OtherKey="IDLocalidad" Type="System_Sis_Tienda" />
      <Association Name="System_Inf_Municipios_System_Inf_Localidades" Member="System_Inf_Municipios" ThisKey="IDMunicipio" OtherKey="IDMunicipio" Type="System_Inf_Municipios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Inf_Municipios" Member="System_Inf_Municipios">
    <Type Name="System_Inf_Municipios">
      <Column Name="IDMunicipio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Inf_Municipios_System_Inf_Localidades" Member="System_Inf_Localidades" ThisKey="IDMunicipio" OtherKey="IDMunicipio" Type="System_Inf_Localidades" />
      <Association Name="System_Inf_Municipios_System_Sis_Tienda" Member="System_Sis_Tienda" ThisKey="IDMunicipio" OtherKey="IDMunicipio" Type="System_Sis_Tienda" />
      <Association Name="System_Inf_Estados_System_Inf_Municipios" Member="System_Inf_Estados" ThisKey="IDEstado" OtherKey="IDEstado" Type="System_Inf_Estados" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_Bitacora" Member="System_Sis_Bitacora">
    <Type Name="System_Sis_Bitacora">
      <Column Name="IDBitacora" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Accion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Association Name="User_Usuarios_System_Sis_Bitacora" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_Notificacion" Member="System_Sis_Notificacion">
    <Type Name="System_Sis_Notificacion">
      <Column Name="IDNotificacion" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FCreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FFin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Sis_Notificacion_System_Sis_Notificacion_Seguimiento" Member="System_Sis_Notificacion_Seguimiento" ThisKey="IDNotificacion" OtherKey="IDNotificacion" Type="System_Sis_Notificacion_Seguimiento" />
      <Association Name="System_Areas_System_Sis_Notificacion" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_Notificacion_Seguimiento" Member="System_Sis_Notificacion_Seguimiento">
    <Type Name="System_Sis_Notificacion_Seguimiento">
      <Column Name="IDSeguimientoNot" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDNotificacion" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FNotificacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="System_Sis_Notificacion_System_Sis_Notificacion_Seguimiento" Member="System_Sis_Notificacion" ThisKey="IDNotificacion" OtherKey="IDNotificacion" Type="System_Sis_Notificacion" IsForeignKey="true" />
      <Association Name="User_Usuarios_System_Sis_Notificacion_Seguimiento" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_Pagina" Member="System_Sis_Pagina">
    <Type Name="System_Sis_Pagina">
      <Column Name="IDPagina" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Abreviatura" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Accion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Controlador" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_PerfilUsuario" Member="System_Sis_PerfilUsuario">
    <Type Name="System_Sis_PerfilUsuario">
      <Column Name="IDPerfil" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Perfil" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Permisos" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Comentarios" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Sis_Tienda" Member="System_Sis_Tienda">
    <Type Name="System_Sis_Tienda">
      <Column Name="IDTienda" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDSupervision" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDSupervisor" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDLider" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDEncargado1" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="E1Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDEncargado2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="E2Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDEncargado3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="E3Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDAuxsiliar1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDAuxsiliar2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDAuxsiliar3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IDEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Calle" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Longitud" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HApertura" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="HCierre" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="IUSACodigo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IUSAUsuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IUSAContraseña" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PCPAYUsuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PCPAYContraseña" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Sis_Tienda_Administration_Evaluacion_Tienda_Resultados" Member="Administration_Evaluacion_Tienda_Resultados" ThisKey="IDTienda" OtherKey="IDTienda" Type="Administration_Evaluacion_Tienda_Resultados" />
      <Association Name="System_Inf_Estados_System_Sis_Tienda" Member="System_Inf_Estados" ThisKey="IDEstado" OtherKey="IDEstado" Type="System_Inf_Estados" IsForeignKey="true" />
      <Association Name="System_Inf_Localidades_System_Sis_Tienda" Member="System_Inf_Localidades" ThisKey="IDLocalidad" OtherKey="IDLocalidad" Type="System_Inf_Localidades" IsForeignKey="true" />
      <Association Name="System_Inf_Municipios_System_Sis_Tienda" Member="System_Inf_Municipios" ThisKey="IDMunicipio" OtherKey="IDMunicipio" Type="System_Inf_Municipios" IsForeignKey="true" />
      <Association Name="System_Supervision_System_Sis_Tienda" Member="System_Supervision" ThisKey="IDSupervision" OtherKey="IDSupervision" Type="System_Supervision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.System_Supervision" Member="System_Supervision">
    <Type Name="System_Supervision">
      <Column Name="IDSupervision" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Supervision" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDTiendas" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Tiendas" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="System_Supervision_System_Sis_Tienda" Member="System_Sis_Tienda" ThisKey="IDSupervision" OtherKey="IDSupervision" Type="System_Sis_Tienda" />
      <Association Name="User_Usuarios_System_Supervision" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cuestionario" Member="Trainig_Cuestionario">
    <Type Name="Trainig_Cuestionario">
      <Column Name="IDCuestionario" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoCuestionario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NombreAs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Usuarios" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="NoPreguntas" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoRespuestas" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Calificacion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Preguntas" Member="Trainig_Cuestionario_Preguntas" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario_Preguntas" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Respuestas" Member="Trainig_Cuestionario_Respuestas" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario_Respuestas" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Respuestas_User" Member="Trainig_Cuestionario_Respuestas_User" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario_Respuestas_User" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Seguimiento" Member="Trainig_Cuestionario_Seguimiento" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario_Seguimiento" />
      <Association Name="System_Areas_Trainig_Cuestionario" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="User_Usuarios_Trainig_Cuestionario" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cuestionario_Preguntas" Member="Trainig_Cuestionario_Preguntas">
    <Type Name="Trainig_Cuestionario_Preguntas">
      <Column Name="IDPregunta" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCuestionario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoPregunta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pregunta" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IDRespuesta" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Valor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cuestionario_Preguntas_Trainig_Cuestionario_Respuestas" Member="Trainig_Cuestionario_Respuestas" ThisKey="IDPregunta" OtherKey="IDPregunta" Type="Trainig_Cuestionario_Respuestas" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Preguntas" Member="Trainig_Cuestionario" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cuestionario_Respuestas" Member="Trainig_Cuestionario_Respuestas">
    <Type Name="Trainig_Cuestionario_Respuestas">
      <Column Name="IDRespuesta" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPregunta" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDCuestionario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoRespuesta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Respuesta" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Respuestas" Member="Trainig_Cuestionario" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario" IsForeignKey="true" />
      <Association Name="Trainig_Cuestionario_Preguntas_Trainig_Cuestionario_Respuestas" Member="Trainig_Cuestionario_Preguntas" ThisKey="IDPregunta" OtherKey="IDPregunta" Type="Trainig_Cuestionario_Preguntas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cuestionario_Respuestas_User" Member="Trainig_Cuestionario_Respuestas_User">
    <Type Name="Trainig_Cuestionario_Respuestas_User">
      <Column Name="IDRespuestas" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCuestionario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Respuestas" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Respuestas_User" Member="Trainig_Cuestionario" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario" IsForeignKey="true" />
      <Association Name="User_Usuarios_Trainig_Cuestionario_Respuestas_User" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cuestionario_Seguimiento" Member="Trainig_Cuestionario_Seguimiento">
    <Type Name="Trainig_Cuestionario_Seguimiento">
      <Column Name="IDCuestionarioSeg" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCuestionario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Avance" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cuestionario_Trainig_Cuestionario_Seguimiento" Member="Trainig_Cuestionario" ThisKey="IDCuestionario" OtherKey="IDCuestionario" Type="Trainig_Cuestionario" IsForeignKey="true" />
      <Association Name="User_Usuarios_Trainig_Cuestionario_Seguimiento" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cursos" Member="Trainig_Cursos">
    <Type Name="Trainig_Cursos">
      <Column Name="IDCurso" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoCurso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDArea" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreA" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IDSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NombreAs" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Usuarios" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="FInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cursos_Trainig_Cursos_Seguimiento" Member="Trainig_Cursos_Seguimiento" ThisKey="IDCurso" OtherKey="IDCurso" Type="Trainig_Cursos_Seguimiento" />
      <Association Name="Trainig_Cursos_Trainig_Cursos_Temas" Member="Trainig_Cursos_Temas" ThisKey="IDCurso" OtherKey="IDCurso" Type="Trainig_Cursos_Temas" />
      <Association Name="System_Areas_Trainig_Cursos" Member="System_Areas" ThisKey="IDArea" OtherKey="IDArea" Type="System_Areas" IsForeignKey="true" />
      <Association Name="User_Usuarios_Trainig_Cursos" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cursos_Seguimiento" Member="Trainig_Cursos_Seguimiento">
    <Type Name="Trainig_Cursos_Seguimiento">
      <Column Name="IDCursosSeg" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCurso" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDUsuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Avance" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cursos_Trainig_Cursos_Seguimiento" Member="Trainig_Cursos" ThisKey="IDCurso" OtherKey="IDCurso" Type="Trainig_Cursos" IsForeignKey="true" />
      <Association Name="User_Usuarios_Trainig_Cursos_Seguimiento" Member="User_Usuarios" ThisKey="IDUsuario" OtherKey="IDUsuario" Type="User_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trainig_Cursos_Temas" Member="Trainig_Cursos_Temas">
    <Type Name="Trainig_Cursos_Temas">
      <Column Name="IDTema" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCurso" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NoTema" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tema" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Recurso" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trainig_Cursos_Trainig_Cursos_Temas" Member="Trainig_Cursos" ThisKey="IDCurso" OtherKey="IDCurso" Type="Trainig_Cursos" IsForeignKey="true" />
    </Type>
  </Table>
</Database>